#pragma once
#define STATUS_OK 0
#define SOCKET_CREATION_FAILED -1
#define SETSOCKOPT_FAILED -2
#define SOCKET_BINDING_FAILED -3
#define LISTEN_FAILED -4
#define SERVER_ACCEPT_FAILED -5
#define SOCKET_CLOSING_FAILED -6
#define SEND_FAILED -7
#define READ_FAILED -8
#define CANNOT_OPEN_FILE -9
#define CONNECT_FAILED -10